Rename columns
swcarpentry/r-novice-gapminder pull request #663
Opened 2020-10-16 16:10 UTC by stefpiatek

Here's a quick go at adding in how to rename columns. Didn't feel like it was worth adding it as a new commonly used verbs to dplyr so just tagged it onto the end of the select, as they're already dealing with columns there. Let me know what you think. 

Also figure I may as well try and get this to count to hacktoberfest when you're happy with it. Looks like you'd need to either tag the PR or the repository as a whole if that's not too much hassle!

Answers swcarpentry/r-novice-gapminder#660

2020-10-18 01:20 UTC, naupaka requested changes
Thanks for the PR @stefpiatek! I've made some suggestions that mostly have to do with style and grammar issues. I am not sure if the Carpentries are participating in Hacktober? @jcoliver may know more. I know there were some issues with lots of spam across a number of the lesson repos.

2020-10-18 01:20 UTC, naupaka commented on _episodes_rmd/13-dplyr.Rmd
> +> In Chapter 4 we covered how you can rename columns with base R by assigning a value to the output of the `names` function. Just like select, this is a bit cumbersome, but thankfully dplyr has a `re
For Carpentries R style, we prefer functions to be followed by parentheses for distinguishing them from other objects (e.g. `names()`, `select()`, and `rename()`)

2020-10-18 01:20 UTC, naupaka commented on _episodes_rmd/04-data-structures-part1.Rmd
> +> Dataframes have column names we can access them like we did with vectors
Grammar: "Dataframes have column names we can access them like we did with vectors" -> "Data frames have column names, which can be accessed with the `names()` function."

2020-10-18 01:20 UTC, naupaka commented on _episodes_rmd/04-data-structures-part1.Rmd
> +> ## Tip: Renaming dataframe columns
dataframe -> data frame

2020-10-18 01:20 UTC, naupaka commented on _episodes_rmd/04-data-structures-part1.Rmd
> +> If you want to rename the second column you can assign the new name to the second element of names
Grammar: "If you want to rename the second column you can assign the new name to the second element of names" -> "If you want to rename the second column, you can assign a new name to the second element of `names(cats)`."

2020-10-18 01:20 UTC, naupaka commented on _episodes_rmd/13-dplyr.Rmd
> +> Within a pipeline, it's used as `rename(new_name = old_name)`. For example we may want to rename the gdpPercap column name from our select statement above.
"it's used as" -> "the syntax is"

2020-10-18 01:20 UTC, naupaka commented on _episodes_rmd/13-dplyr.Rmd
> +> Within a pipeline, it's used as `rename(new_name = old_name)`. For example we may want to rename the gdpPercap column name from our select statement above.
Grammar: "For example we may want to rename the gdpPercap column name from our select statement above." -> "For example, we may want to rename the `gdpPercap` column name from our `select()` statement above."

2020-10-24 10:55 UTC, stefpiatek commented
Thanks for the feedback - should all be addressed now but let me know if you spot anything else that needs changing. 

No worries if hacktoberfest isn't something that the carpentries are doing.

2020-10-25 02:06 UTC, naupaka commented on _episodes_rmd/13-dplyr.Rmd
> +> Just like select, this is a bit cumbersome, but thankfully dplyr has a `rename` function.
Please add parentheses after rename

2020-10-25 02:07 UTC, naupaka commented
Need to add parentheses in one place and then it should be good to merge.

@fmichonneau what's the current status of Carpentries and Hacktober?

2020-10-25 15:46 UTC, stefpiatek commented on _episodes_rmd/13-dplyr.Rmd
> +> Just like select, this is a bit cumbersome, but thankfully dplyr has a `rename` function.
ah so close, good spot

2020-10-25 16:12 UTC, naupaka approved these changes

2020-10-25 16:13 UTC, naupaka commented
Looks good to me. I will wait a few days to see if @fmichonneau has an update re: Hacktober, otherwise this is ready to merge.

2020-10-26 08:20 UTC, fmichonneau commented
@stefpiatek I added the `hacktoberfest-accepted` which should be enough for your contribution to count. Could you please check your dashboard and get back to us if you don't see your PR there?

2020-10-26 09:19 UTC, stefpiatek commented
> @stefpiatek I added the `hacktoberfest-accepted` which should be enough for your contribution to count. Could you please check your dashboard and get back to us if you don't see your PR there?

Thanks @fmichonneau, yep it's in my dashboard - thanks!

2020-10-26 20:18 UTC, naupaka commented
Thanks all!

2020-10-26 20:18 UTC, merged