Fix output of ls() function in Lesson 1 RStudio intro
swcarpentry/r-novice-gapminder pull request #781
Opened 2022-05-13 01:46 UTC by kthayashi

I noticed that the output of the `ls()` function in Lesson 1 (RStudio intro) presently contains a number of extra items (`args`, `dest_md`, `op`, `src_rmd`) that learners shouldn't see on their end if following along in the lesson. This probably comes from the usage of the [`generate_md_episodes()`](https://github.com/swcarpentry/r-novice-gapminder/blob/6c0b1812d9b04c95ad8176ae18eb34a9d86ea65a/bin/generate_md_episodes.R) function, as noted in discussion of #178. The relevant code is on [line 448](https://github.com/swcarpentry/r-novice-gapminder/blob/4b5dbd88b97379f97c8c6a54762fe6461e1e8260/_episodes_rmd/01-rstudio-intro.Rmd#L448) of the Lesson 1 Rmd file.

I've implemented a surface-level solution by defining a temporary environment that contains only the variables that learners should have on their end (`x` and `y`) and using this to generate the `ls()` output. This doesn't address the root of the issue, but at least should align the rendered lesson with what learners should be seeing on their end.

2022-10-14 18:29 UTC, naupaka requested changes
@kthayashi thanks for noticing this and for the clever fix. Could you add a comment to the new chunk to explain the reasoning and logic so that future contributors/maintainers understand the reasoning behind the otherwise potentially cryptic chunk?

2023-04-19 16:25 UTC, matthieu-bruneaux commented
Thanks @kthayashi and @naupaka!

I added an explanatory comment to the chunk (mostly taking from the PR comment from @kthayashi above).

LGTM for merging (cc @skanwal or @naupaka to confirm).

2023-04-19 23:47 UTC, skanwal approved these changes
Thanks for picking this up and proposing a fix. It looks good to me as well.

2023-04-20 11:20 UTC, merged

2023-04-20 11:20 UTC, matthieu-bruneaux commented
Thank you @skanwal!