add instructor note, closes #870
swcarpentry/r-novice-gapminder pull request #871
Opened 2023-11-02 14:31 UTC by ha0ye

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._

_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._

_If any relevant discussions have taken place elsewhere, please provide links to these._

<details>

For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).

Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

</details>

2023-11-08 22:57 UTC, skanwal requested changes
Thanks @ha0ye for suggesting this update.

I was reading through this issue online https://github.com/rstudio/rstudio/issues/13118 - looks like even after updating the global setting in Rstudio, the issue persists for few users. It's a WIP, so I suggest we keep an eye on it before merging the change.

2023-11-08 22:57 UTC, skanwal commented on instructors/instructor-notes.md
> +This option can be turned off an on in the following menu setting:
minor typo here "turned off and **on**"

2024-01-12 04:26 UTC, skanwal approved these changes
The issue has been fixed https://github.com/rstudio/rstudio/issues/13118#issuecomment-1814939652. 

This looks good to me now. I have fixed the typo.
Thoughts @matthieu-bruneaux ?

2024-01-12 04:26 UTC, skanwal commented on instructors/instructor-notes.md
> +This option can be turned off an on in the following menu setting:
updated in [`6dab42c` (#871)](https://github.com/swcarpentry/r-novice-gapminder/pull/871/commits/6dab42cb895d37c4a3663d84c8de20752af690ee)

2024-01-19 19:40 UTC, naupaka commented
I can verify that this is now fixed for me. But a useful addition. I am going to merge.

2024-01-19 19:41 UTC, merged